apiVersion: v1
kind: ConfigMap
metadata:
  name: dap-service-config
data:
  application.yaml: |
    server:
      port: 8082

    spring:
      application:
        name: quay-management-api
      profiles:
        active: ${ACTIVE_PROFILE:dev}

    # Common configuration for all profiles
    # Blockchain configuration
    blockchain:
      ethereum:
        rpc:
          http: http://157.173.119.195:8545
          ws: ws://157.173.119.195:8546

    logging:
      level:
        root: INFO
        com.portnet.dockchain: DEBUG

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operations-sorter: method 