apiVersion: v1
kind: ConfigMap
metadata:
  name: dap-service-dev-config
  labels:
    app: dap-service
    environment: development
data:
  application-dev.yaml: |
    # Development Profile
    spring:
      datasource:
        url: jdbc:mysql://mysql:3306/TradeChain?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            format_sql: true

      rabbitmq:
        host: rabbitmq
        port: 5672
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
        virtual-host: /

    # Enhanced logging for development
    logging:
      level:
        org.springframework.amqp: DEBUG
        org.springframework.boot.autoconfigure.amqp: DEBUG 