version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: dockchain-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dockchain-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql-data: