apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app: rabbitmq
data:
  enabled_plugins: |
    [
      rabbitmq_management,
      rabbitmq_peer_discovery_k8s
    ].
  rabbitmq.conf: |
    ## Cluster formation. See https://www.rabbitmq.com/cluster-formation.html for details.
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    ## Should RabbitMQ node name be computed from the pod's hostname or IP address?
    ## IP addresses are not stable, so using [stable] hostnames is recommended for a K8s environment.
    cluster_formation.k8s.address_type = hostname
    ## How often should node cleanup checks run?
    cluster_formation.node_cleanup.interval = 30
    ## Set to false if automatic removal of unknown/absent nodes
    ## is desired. This can be dangerous, see
    ##  https://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    ## Queue master locator
    queue_master_locator = min-masters
    ## Enable MQTT plugin
    mqtt.default_user = guest
    mqtt.default_pass = guest
    mqtt.allow_anonymous = true 