spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    org.springframework.amqp: DEBUG
    org.hibernate.SQL: DEBUG