apiVersion: v1
kind: ConfigMap
metadata:
  name: ship-management-dev-config
  labels:
    app: ship-management-service
    environment: development
data:
  application-dev.properties: |
    #-----------------
    # DEV PROFILE
    #-----------------
    # Database configuration for dev profile
    spring.datasource.url=jdbc:mysql://mysql:3306/TradeChain?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    spring.datasource.username=${MYSQL_USER}
    spring.datasource.password=${MYSQL_PASSWORD}
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

    # Hibernate configuration for development
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true

    # RabbitMQ configuration for dev profile
    spring.rabbitmq.host=rabbitmq
    spring.rabbitmq.port=5672
    spring.rabbitmq.username=${RABBITMQ_USER}
    spring.rabbitmq.password=${RABBITMQ_PASSWORD}
    spring.rabbitmq.virtual-host=/

    # Logging for development
    logging.level.org.springframework.amqp=DEBUG
    logging.level.org.springframework.boot.autoconfigure.amqp=DEBUG 